/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package app;

import dao.BangDiemDao;
import dao.SinhVienDao;
import database.DataValidator;
import database.MessageDialog;
import java.awt.Color;
import java.util.Collections;
import java.util.Comparator;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import model.BangDiem;
import model.SinhVien;

/**
 *
 * @author Dell
 */
public class GPAManagementPanel extends javax.swing.JPanel {

    private MainForm parent;
    private DefaultTableModel tblModel;
    // private DefaultTableModel tblModelID;

    /**
     * Creates new form GPAManagementPanel
     */
    public GPAManagementPanel() {
        initComponents();

        initTableID();

        loadDataToTableID();

        initTableGPA();

        loadDataToTable();

    }

    private void initTableGPA() {
        tblModel = new DefaultTableModel();
        tblModel.setColumnIdentifiers(new String[]{"Mã Sinh Viên", "Họ Tên", "Điểm tp1", "Điểm tp2", "Điểm cuối kỳ", "Điểm TB"});
        tblGpa.setModel(tblModel);
    }

    private void initTableID() {
        tblModel = new DefaultTableModel();
        tblModel.setColumnIdentifiers(new String[]{"Mã Sinh Viên"});
        tblID.setModel(tblModel);
    }

    private void loadDataToTableID() {
        List<SinhVien> ds = SinhVienDao.findAll1();
        tblModel.setRowCount(0);
        for (SinhVien sv1 : ds) {
            tblModel.addRow(new Object[]{
                sv1.getMaSinhVien()
            });
        }
        //tblModelID.fireTableDataChanged(); // đảm bảo dữ liệu sau khi thay đổi được hiển thị trên bảng
    }

    private void loadDataToTable() {
        List<BangDiem> listbd = BangDiemDao.findAll1();
        List<SinhVien> listsv = SinhVienDao.findAll1();
        SinhVien sv = new SinhVien();

        tblModel.setRowCount(0);
        for (BangDiem bd : listbd) {
            sv.setMaSinhVien(bd.getMaSinhVien());
            SinhVienDao.search(sv);

            float gpa = (bd.getThanhPhan1() * 1) / 10 + (bd.getThanhPhan2() * 2) / 10 + (bd.getCuoiKy() * 7) / 10;
            tblModel.addRow(new Object[]{
                bd.getMaSinhVien(), sv.getHoTen(), bd.getThanhPhan1(), bd.getThanhPhan2(), bd.getCuoiKy(), gpa
            });
        }
        tblModel.fireTableDataChanged(); // đảm bảo dữ liệu sau khi thay đổi được hiển thị trên bảng
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtStudentIdSearch = new javax.swing.JTextField();
        bntSearch = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtStudentID = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtTP1 = new javax.swing.JTextField();
        txtTP2 = new javax.swing.JTextField();
        txtCK = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        btnNew = new javax.swing.JButton();
        bntSave = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblGpa = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        lblGpa = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblID = new javax.swing.JTable();

        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Quản lý điểm");

        jLabel3.setText("Mã Sinh Viên");

        txtStudentIdSearch.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtStudentIdSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStudentIdSearchActionPerformed(evt);
            }
        });

        bntSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/search-icon-16.png"))); // NOI18N
        bntSearch.setText("Tìm Kiếm");
        bntSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(txtStudentIdSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bntSearch)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtStudentIdSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bntSearch))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jLabel4.setText("Mã Sinh Viên:");

        jLabel5.setText("Họ Tên:");

        jLabel6.setText("Thành Phần 1:");

        jLabel7.setText("Thành Phần 2:");

        jLabel8.setText("Cuối kỳ:");

        txtTP1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtTP2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtCK.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(44, 44, 44)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTP2)
                    .addComponent(txtCK)
                    .addComponent(txtStudentID, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtName)
                    .addComponent(txtTP1))
                .addGap(16, 16, 16))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(txtStudentID, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtTP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(txtTP2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(txtCK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        btnNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/new-icon-16.png"))); // NOI18N
        btnNew.setText("Tạo Mới");
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });

        bntSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Save-icon.png"))); // NOI18N
        bntSave.setText("Lưu");
        bntSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntSaveActionPerformed(evt);
            }
        });

        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Actions-edit-delete-icon-16.png"))); // NOI18N
        btnDelete.setText("Xóa");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Actions-document-edit-icon-16.png"))); // NOI18N
        btnUpdate.setText("Cập Nhật");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        tblGpa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblGpa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblGpaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblGpa);

        jLabel9.setText("Điểm TB:");

        lblGpa.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblGpa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGpa.setText("10");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(lblGpa))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel9)))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(lblGpa)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/gpa-icon.png"))); // NOI18N
        jButton1.setText("Sort");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tblID.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Title 1"
            }
        ));
        jScrollPane3.setViewportView(tblID);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addComponent(jSeparator1)
                    .addComponent(jSeparator2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(btnNew)
                                .addGap(18, 18, 18)
                                .addComponent(bntSave)
                                .addGap(18, 18, 18)
                                .addComponent(btnDelete)
                                .addGap(18, 18, 18)
                                .addComponent(btnUpdate)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnNew)
                            .addComponent(bntSave)
                            .addComponent(btnDelete)
                            .addComponent(btnUpdate)
                            .addComponent(jButton1)))
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(40, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtStudentIdSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStudentIdSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStudentIdSearchActionPerformed

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        // TODO add your handling code here:
        txtTP2.setText("");
        txtTP1.setText("");
        txtCK.setText("");
        txtName.setText("");
        txtStudentIdSearch.setText("");
        txtStudentID.setText("");
        txtStudentID.setBackground(Color.white);
        lblGpa.setText("0");

    }//GEN-LAST:event_btnNewActionPerformed

    private void bntSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntSaveActionPerformed
        // TODO add your handling code here:
        int flas = 0;
        StringBuilder sb = new StringBuilder();
        DataValidator.validateEmpty(txtStudentID, sb, "Không để trống mã sinh viên");
        if (sb.length() > 0) {
            MessageDialog.showErrorDialog(parent, sb.toString(), "Lỗi");
            return;
        }
        BangDiem bd = new BangDiem();
        List<SinhVien> list = SinhVienDao.findAll1();
        for (SinhVien sv : list) {
            if (sv.getMaSinhVien().equals(txtStudentID.getText())) {
                flas = 1;
                txtName.setText(sv.getHoTen());
                bd.setMaSinhVien(txtStudentID.getText());
                bd.setThanhPhan1(Float.parseFloat(txtTP1.getText()));
                bd.setThanhPhan2(Float.parseFloat(txtTP2.getText()));
                bd.setCuoiKy(Float.parseFloat(txtCK.getText()));
            }
        }
        if (flas == 0) {
            MessageDialog.showMessageDialog(parent, "Mã sinh viên không tồn tại", "Thông báo");
        } else {
            try {
                BangDiemDao.insert(bd);
                float gpa = (bd.getThanhPhan1() * 1) / 10 + (bd.getThanhPhan2() * 2) / 10 + (bd.getCuoiKy() * 7) / 10;
                lblGpa.setText(String.valueOf(gpa));
                MessageDialog.showMessageDialog(parent, "Bảng điểm đã được lưu", "Thông báo");
                loadDataToTable(); // cập nhật lại dữ liệu chứa trong bảng.
            } catch (Exception e) {
                MessageDialog.showErrorDialog(parent, e.getMessage(), "Lỗi");
            }
        }


    }//GEN-LAST:event_bntSaveActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        StringBuilder sb = new StringBuilder();
        DataValidator.validateEmpty(txtStudentID, sb, "Không để trống mã sinh viên");

        if (sb.length() > 0) {
            MessageDialog.showErrorDialog(parent, sb.toString(), "Lỗi");
            return;
        }
        BangDiem bd = new BangDiem();
        bd.setThanhPhan1(Float.parseFloat(txtTP1.getText()));
        bd.setThanhPhan2(Float.parseFloat(txtTP2.getText()));
        bd.setCuoiKy(Float.parseFloat(txtCK.getText()));
        bd.setMaSinhVien(txtStudentID.getText());
        try {
            BangDiemDao.update(bd);
            float gpa = (bd.getThanhPhan1() * 1) / 10 + (bd.getThanhPhan2() * 2) / 10 + (bd.getCuoiKy() * 7) / 10;
            lblGpa.setText(String.valueOf(gpa));
            MessageDialog.showMessageDialog(parent, "Bảng điểm đã được cập nhật", "Thông báo");
            loadDataToTable();
        } catch (Exception e) {
            MessageDialog.showErrorDialog(parent, e.getMessage(), "Lỗi");
        }

    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        StringBuilder sb = new StringBuilder();
        DataValidator.validateEmpty(txtStudentID, sb, "Không để trống mã sinh viên");

        if (sb.length() > 0) {
            MessageDialog.showErrorDialog(parent, sb.toString(), "Lỗi");
            return;
        }
        BangDiem bd = new BangDiem();
        bd.setMaSinhVien(txtStudentID.getText());
        try {
            BangDiemDao.delete(bd);
            lblGpa.setText("0");
            MessageDialog.showMessageDialog(parent, "Bảng điểm đã được xóa", "Thông báo");
            loadDataToTable();
        } catch (Exception e) {
            MessageDialog.showErrorDialog(parent, e.getMessage(), "Lỗi");
        }

    }//GEN-LAST:event_btnDeleteActionPerformed

    private void bntSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntSearchActionPerformed
        // TODO add your handling code here:
        int flas = 0;
        StringBuilder sb = new StringBuilder();
        DataValidator.validateEmpty(txtStudentIdSearch, sb, "Không để trống mã sinh viên");

        if (sb.length() > 0) {
            MessageDialog.showErrorDialog(parent, sb.toString(), "Lỗi");
            return;
        }
        try {
            BangDiem bd = new BangDiem();
            bd.setMaSinhVien(txtStudentIdSearch.getText());
            List<SinhVien> list = SinhVienDao.findAll1();
            for (SinhVien sv : list) {
                if (sv.getMaSinhVien().equals(bd.getMaSinhVien())) {
                    flas = 1;
                    // System.out.println("hi");
                    BangDiemDao.search(bd);
                    txtName.setText(sv.getHoTen());
                    txtStudentID.setText(bd.getMaSinhVien());
                    txtTP1.setText(String.valueOf(bd.getThanhPhan2()));
                    txtTP2.setText(String.valueOf(bd.getThanhPhan2()));
                    txtCK.setText(String.valueOf(bd.getCuoiKy()));
                    //  System.out.println("hi2");
                    float gpa = (bd.getThanhPhan1() * 1) / 10 + (bd.getThanhPhan2() * 2) / 10 + (bd.getCuoiKy() * 7) / 10;
                    lblGpa.setText(String.valueOf(gpa));
                }
            }
            if (flas == 0) {
                MessageDialog.showMessageDialog(parent, "Mã sinh viên không tồn tại", "Thông báo");
                return;
            }
            //loadDataToTable();

        } catch (Exception e) {

            MessageDialog.showErrorDialog(parent, e.getMessage(), "Lỗi");
        }
    }//GEN-LAST:event_bntSearchActionPerformed

    private void tblGpaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblGpaMouseClicked
        // TODO add your handling code here:
        // TODO add your handling code here:
        try {
            int row = tblGpa.getSelectedRow();
            if (row >= 0) {
                String id = (String) tblGpa.getValueAt(row, 0);
                BangDiem bd = new BangDiem();
                SinhVien sv = new SinhVien();
                bd.setMaSinhVien(id);
                sv.setMaSinhVien(id);
                SinhVienDao.search(sv);
                BangDiemDao.search(bd);
                if (bd != null) {
                    txtName.setText(sv.getHoTen());
                    txtStudentID.setText(bd.getMaSinhVien());
                    txtTP1.setText(String.valueOf(bd.getThanhPhan1()));
                    txtTP2.setText(String.valueOf(bd.getThanhPhan2()));
                    txtCK.setText(String.valueOf(bd.getCuoiKy()));
                    float gpa = (bd.getThanhPhan1() * 1) / 10 + (bd.getThanhPhan2() * 2) / 10 + (bd.getCuoiKy() * 7) / 10;
                    lblGpa.setText(String.valueOf(gpa));
                }
            }
        } catch (Exception e) {
            MessageDialog.showErrorDialog(parent, e.getMessage(), "Lỗi");
        }
    }//GEN-LAST:event_tblGpaMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        List<BangDiem> listbd = BangDiemDao.findAll1();
        SinhVien sv = new SinhVien();
        Collections.sort(listbd, (BangDiem bd1, BangDiem bd2) -> (int) (((bd2.getThanhPhan1() * 1) / 10 + (bd2.getThanhPhan2() * 2) / 10 + (bd2.getCuoiKy() * 7) / 10) * 10
                - ((bd1.getThanhPhan1() * 1) / 10 + (bd1.getThanhPhan2() * 2) / 10 + (bd1.getCuoiKy() * 7) / 10) * 10));
        tblModel.setRowCount(0);
        for (BangDiem bd : listbd) {
            sv.setMaSinhVien(bd.getMaSinhVien());
            SinhVienDao.search(sv);

            float gpa = (bd.getThanhPhan1() * 1) / 10 + (bd.getThanhPhan2() * 2) / 10 + (bd.getCuoiKy() * 7) / 10;
            tblModel.addRow(new Object[]{
                bd.getMaSinhVien(), sv.getHoTen(), bd.getThanhPhan1(), bd.getThanhPhan2(), bd.getCuoiKy(), gpa
            });
        }
        tblModel.fireTableDataChanged(); // đảm bảo dữ liệu sau khi thay đổi được hiển thị trên bảng
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntSave;
    private javax.swing.JButton bntSearch;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblGpa;
    private javax.swing.JTable tblGpa;
    private javax.swing.JTable tblID;
    private javax.swing.JTextField txtCK;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtStudentID;
    private javax.swing.JTextField txtStudentIdSearch;
    private javax.swing.JTextField txtTP1;
    private javax.swing.JTextField txtTP2;
    // End of variables declaration//GEN-END:variables
}
